### ISSUE TITLE
getting AttributeError: 'NoneType' object has no attribute 'strip' when trying the sample code

### ISSUE THREAD

**Issue by jackxpeng** [gintas/django-picklefield#14]
When I try the example code, I'm getting an error. Can someone help? Thanks.
model:

from picklefield import PickledObjectField
 
class SomeObject(models.Model):
    args = PickledObjectField()
 
manage.py shell:
 
from scratch.models import SomeObject
obj = SomeObject()
obj.args = ['a', {'a':3}]
obj.save()

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/django/db/backends/util.py", line 73, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/mysql/connector/django/base.py", line 330, in last_executed_query
    return cursor.statement
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/mysql/connector/django/base.py", line 129, in __getattr__
    return getattr(self.cursor, attr)
  File "/home/jack/workspace/venv0/lib/python3.3/site-packages/mysql/connector/cursor.py", line 868, in statement
    return self._executed.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by charettes** [comment]
This issue seems related to the `mysql` package.
