### ISSUE TITLE
Django 3.2 test failure due to DEFAULT_AUTO_FIELD

### ISSUE THREAD

**Issue by jayvdb** [gintas/django-picklefield#58]
Django 3.2 is emitting additional warnings, which is causing two tests to fail.
```
[   28s] ======================================================================
[   28s] FAIL: test_mutable_default_check (tests.tests.PickledObjectFieldCheckTests)
[   28s] ----------------------------------------------------------------------
[   28s] Traceback (most recent call last):
[   28s]   File "/home/abuild/rpmbuild/BUILD/django-picklefield-3.0.1/tests/tests.py", line 243, in test_mutable_default_check
[   28s]     id='picklefield.E001',
[   28s] AssertionError: Lists differ: [<War[905 chars]001'>, <Warning: level=30, msg="Auto-created p[378 chars]42'>] != [<War[905 chars]001'>]
[   28s] 
[   28s] First list contains 1 additional elements.
[   28s] First extra element 3:
[   28s] <Warning: level=30, msg="Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.", hint="Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.", obj=<class 'tests.tests.PickledObjectFieldCheckTests.test_mutable_default_check.<locals>.Model'>, id='models.W042'>
[   28s] 
[   28s] Diff is 2280 characters long. Set self.maxDiff to None to see it.
[   28s] 
[   28s] ======================================================================
[   28s] FAIL: test_non_mutable_default_check (tests.tests.PickledObjectFieldCheckTests)
[   28s] ----------------------------------------------------------------------
[   28s] Traceback (most recent call last):
[   28s]   File "/home/abuild/rpmbuild/BUILD/django-picklefield-3.0.1/tests/tests.py", line 253, in test_non_mutable_default_check
[   28s]     self.assertEqual(Model().check(), [])
[   28s] AssertionError: Lists differ: [<Warning: level=30, msg="Auto-created pri[380 chars]42'>] != []
[   28s] 
[   28s] First list contains 1 additional elements.
[   28s] First extra element 0:
[   28s] <Warning: level=30, msg="Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.", hint="Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.", obj=<class 'tests.tests.PickledObjectFieldCheckTests.test_non_mutable_default_check.<locals>.Model'>, id='models.W042'>
[   28s] 
[   28s] - [<Warning: level=30, msg="Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.", hint="Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.", obj=<class 'tests.tests.PickledObjectFieldCheckTests.test_non_mutable_default_check.<locals>.Model'>, id='models.W042'>]
[   28s] + []
```

**Comment by charettes** [comment]
Should be fixed now.
